version: 0.1

phases:
  build:
    commands:
      - docker build -t myrepo .

  post_build:
    commands:
      - aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 395893388747.dkr.ecr.sa-east-1.amazonaws.com
      - docker tag myrepo:latest 395893388747.dkr.ecr.sa-east-1.amazonaws.com/myrepo:latest
      - docker push 395893388747.dkr.ecr.sa-east-1.amazonaws.com/myrepo:latest

artifacts:
  files:
    - '**/*'
  base-directory: base_dir
  name: build-artifact-name
  discard-paths: no      