version: 0.1

phases:
  build:
    commands:
      - docker build -t myrepo .

  post_build:
    commands:
      - eval `aws ecr get-login --region sa-east-1`
      - docker tag myrepo:latest 395893388747.dkr.ecr.sa-east-1.amazonaws.com/myrepo:latest
      - docker push 395893388747.dkr.ecr.sa-east-1.amazonaws.com/myrepo:latest